### ISSUE TITLE
Donut falls is missing main.nf

### ISSUE THREAD

**Issue by erinyoung** [UPHL-BioNGS/ICA_Modified_Nextflow_Scripts#2]
https://github.com/UPHL-BioNGS/ICA_Modified_Nextflow_Scripts/tree/main/UPHL-BioNGS_Donut_falls does not have main.nf

I don't actually know if this is an issue.

**Comment by jwarnn** [comment]
This is an issue. It is also missing the config file. Thanks.

**Comment by jwarnn** [comment]
This will be addressed with PR #5 .
