### ISSUE TITLE
Update Grandeur V2 

### ISSUE THREAD

**Issue by erinyoung** [UPHL-BioNGS/ICA_Modified_Nextflow_Scripts#7]
I'm creating an issue so I get reminders to work on this "this week". 

For CLIA validation, we need to get Grandeur validated for both the linux workstation and ICA. This will involve X samples... likely 10 of each relevant organism. 

I'm currently waiting on an email for AMR gene detection.

**Comment by erinyoung** [comment]
Or Grandeur 3.0! https://github.com/UPHL-BioNGS/ICA_Modified_Nextflow_Scripts/pull/10 addresses this issue.

**Comment by jwarnn** [comment]
We have updated to Grandeur V3. I am going to close this issue.
